version: '3.8'
services:
  libserv:
    build: libserv
    image: libserv-image
    container_name: libserv
    ports:
      - "8182:8182"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/librarian

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: db_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=librarian
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot